#!/bin/bash
set -eu

CONFIG_FILE="${GRIDRUNNER_WIFI_CONFIG:-$HOME/.config/gridrunner/wifi-fallback.env}"
HOTSPOT="${HOTSPOT:-GRIDRUNNER-HOTSPOT}"
HOTSPOT_SSID="${HOTSPOT_SSID:-$HOTSPOT}"
HOTSPOT_PASSWORD="${HOTSPOT_PASSWORD:-}"
HOTSPOT_ALIASES="${HOTSPOT_ALIASES:-Gridrunner-hotspot DEVICE-HOTSPOT}"

shell_quote() {
  local value="$1"

  printf "'%s'" "$(printf '%s' "$value" | sed "s/'/'\\\\''/g")"
}

prompt_if_interactive() {
  local password_confirm=""

  if [ "${GRIDRUNNER_NONINTERACTIVE:-0}" = "1" ]; then
    echo "Non-interactive setup requested; keeping hotspot defaults."
    echo "Set HOTSPOT_SSID and HOTSPOT_PASSWORD, then rerun this script to configure the fallback hotspot."
    return 0
  fi

  if [ ! -r /dev/tty ]; then
    echo "No interactive terminal; keeping hotspot defaults."
    echo "Set HOTSPOT_SSID and HOTSPOT_PASSWORD, then rerun this script to configure the fallback hotspot."
    return 0
  fi

  printf "Fallback hotspot SSID [%s]: " "$HOTSPOT_SSID"
  read -r input_ssid < /dev/tty
  if [ -n "$input_ssid" ]; then
    HOTSPOT_SSID="$input_ssid"
  fi

  while true; do
    printf "Fallback hotspot password"
    if [ -n "$HOTSPOT_PASSWORD" ]; then
      printf " [already set]"
    fi
    printf ": "
    read -rs input_password < /dev/tty
    printf "\n"

    if [ -z "$input_password" ] && [ -n "$HOTSPOT_PASSWORD" ]; then
      break
    fi

    if [ -z "$input_password" ]; then
      echo "Password left blank; hotspot profile creation will require HOTSPOT_PASSWORD later."
      HOTSPOT_PASSWORD=""
      break
    fi

    if [ "${#input_password}" -lt 8 ]; then
      echo "Password must be at least 8 characters."
      continue
    fi

    printf "Confirm fallback hotspot password: "
    read -rs password_confirm < /dev/tty
    printf "\n"

    if [ "$input_password" != "$password_confirm" ]; then
      echo "Passwords did not match."
      continue
    fi

    HOTSPOT_PASSWORD="$input_password"
    break
  done
}

write_config() {
  local config_dir=""

  config_dir="$(dirname "$CONFIG_FILE")"
  mkdir -p "$config_dir"
  umask 077
  {
    echo "# GRIDRUNNER Wi-Fi fallback configuration."
    echo "# Generated by scripts/configure-wifi-hotspot.sh."
    printf "HOTSPOT=%s\n" "$(shell_quote "$HOTSPOT")"
    printf "HOTSPOT_SSID=%s\n" "$(shell_quote "$HOTSPOT_SSID")"
    printf "HOTSPOT_PASSWORD=%s\n" "$(shell_quote "$HOTSPOT_PASSWORD")"
    printf "HOTSPOT_ALIASES=%s\n" "$(shell_quote "$HOTSPOT_ALIASES")"
  } > "$CONFIG_FILE"
  chmod 0600 "$CONFIG_FILE"
}

prompt_if_interactive
write_config

echo "Wi-Fi fallback config written: $CONFIG_FILE"
echo "Fallback hotspot SSID: $HOTSPOT_SSID"
