#!/bin/bash
set -eu

if [ "$(id -u)" -ne 0 ]; then
  echo "Run with sudo: sudo $0"
  exit 1
fi

OPERATOR_USER="${GRIDRUNNER_OPERATOR_USER:-${SUDO_USER:-}}"
if [ -z "$OPERATOR_USER" ]; then
  echo "Unable to determine operator user. Set GRIDRUNNER_OPERATOR_USER."
  exit 1
fi

SUDOERS_FILE="/etc/sudoers.d/gridrunner"

cat > "$SUDOERS_FILE" <<EOF
# GRIDRUNNER web installer and power controls.
# Generated by scripts/setup-sudoers.sh.
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/apt-get update
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/apt-get install -y *
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/install -m 0644 * /etc/systemd/system/gridrunner-web.service
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/systemctl daemon-reload
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/systemctl enable gridrunner-web.service
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/systemctl poweroff
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/systemctl reboot
EOF

chmod 0440 "$SUDOERS_FILE"
visudo -cf "$SUDOERS_FILE"

echo "GRIDRUNNER sudoers installed for user: $OPERATOR_USER"
