#!/bin/bash
set -eu

if [ "$(id -u)" -ne 0 ]; then
  echo "Run with sudo: sudo $0"
  exit 1
fi

OPERATOR_USER="${GRIDRUNNER_OPERATOR_USER:-${SUDO_USER:-}}"
if [ -z "$OPERATOR_USER" ]; then
  echo "Unable to determine operator user. Set GRIDRUNNER_OPERATOR_USER."
  exit 1
fi

SUDOERS_FILE="/etc/sudoers.d/gridrunner"

cat > "$SUDOERS_FILE" <<EOF
# GRIDRUNNER web installer, Wi-Fi controls, and power controls.
# Generated by scripts/setup-sudoers.sh.
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/apt-get update
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/apt-get install -y *
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/install -m 0644 * /etc/systemd/system/gridrunner-web.service
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/install -m 0644 * /etc/systemd/system/gridrunner-events.service
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/install -m 0644 * /etc/systemd/system/gridrunner-events.timer
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/install -m 0644 * /etc/systemd/system/gridrunner-edge-node-ingest.service
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/install -m 0644 * /etc/systemd/system/gridrunner-plane-tracker.service
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/install -m 0644 * /etc/systemd/system/gridrunner-plane-tracker.timer
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/install -m 0644 * /etc/systemd/system/gridrunner-operator-display.service
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/systemctl daemon-reload
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/systemctl enable gridrunner-web.service
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/systemctl restart gridrunner-web.service
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/systemctl enable --now gridrunner-events.timer
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/systemctl enable --now gridrunner-edge-node-ingest.service
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/systemctl enable --now gridrunner-plane-tracker.timer
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/systemctl enable gridrunner-operator-display.service
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/systemctl enable --now mosquitto.service
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/systemctl restart gridrunner-events.service
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/nmcli radio wifi on
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/nmcli connection up *
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/nmcli connection down *
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/nmcli connection modify *
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/nmcli connection add *
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/systemctl poweroff
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/systemctl reboot
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/bash */scripts/install-adsb-readsb.sh
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/env GRIDRUNNER_HOME=* GRIDRUNNER_STATE_DIR=* GRIDRUNNER_DISPLAY_VENDOR_DRIVER=* GRIDRUNNER_LCD_SHOW_URL=* /usr/bin/bash */scripts/configure-display.sh *
EOF

chmod 0440 "$SUDOERS_FILE"
visudo -cf "$SUDOERS_FILE"

for group in systemd-journal adm; do
  if getent group "$group" >/dev/null 2>&1; then
    usermod -aG "$group" "$OPERATOR_USER"
  fi
done

echo "GRIDRUNNER sudoers installed for user: $OPERATOR_USER"
echo "Journal access groups updated for user: $OPERATOR_USER"
echo "Log out and back in, or reboot, for new group membership to apply."
