#!/bin/bash
set -eu

if [ "$(id -u)" -ne 0 ]; then
  echo "Run with sudo: sudo $0"
  exit 1
fi

OPERATOR_USER="${GRIDRUNNER_OPERATOR_USER:-${SUDO_USER:-}}"
if [ -z "$OPERATOR_USER" ]; then
  echo "Unable to determine operator user. Set GRIDRUNNER_OPERATOR_USER."
  exit 1
fi

SUDOERS_FILE="/etc/sudoers.d/gridrunner"

cat > "$SUDOERS_FILE" <<EOF
# GRIDRUNNER web installer, Wi-Fi controls, and power controls.
# Generated by scripts/setup-sudoers.sh.
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/true
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/env DEBIAN_FRONTEND=noninteractive apt-get update
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/env DEBIAN_FRONTEND=noninteractive apt-get install -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold git curl jq tmux htop
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/env DEBIAN_FRONTEND=noninteractive apt-get install -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold python3 python3-venv python3-pip
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/env DEBIAN_FRONTEND=noninteractive apt-get install -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold rtl-sdr soapysdr-tools
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/env DEBIAN_FRONTEND=noninteractive apt-get install -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold network-manager
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/env DEBIAN_FRONTEND=noninteractive apt-get install -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold mosquitto mosquitto-clients jq
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/env DEBIAN_FRONTEND=noninteractive apt-get install -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold mosquitto-clients jq
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/env DEBIAN_FRONTEND=noninteractive apt-get install -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold git evtest xinput
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/env DEBIAN_FRONTEND=noninteractive apt-get install -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold chromium
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/env DEBIAN_FRONTEND=noninteractive apt-get install -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold chromium-browser
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/env DEBIAN_FRONTEND=noninteractive apt-get install -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold firefox-esr
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/env DEBIAN_FRONTEND=noninteractive apt-get install -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold tmux unclutter
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/env DEBIAN_FRONTEND=noninteractive apt-get install -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold flrig pat
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/install -m 0644 */gridrunner/state/gridrunner-web.service /etc/systemd/system/gridrunner-web.service
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/install -m 0644 */gridrunner/state/gridrunner-events.service /etc/systemd/system/gridrunner-events.service
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/install -m 0644 */gridrunner/state/gridrunner-events.timer /etc/systemd/system/gridrunner-events.timer
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/install -m 0644 */gridrunner/state/gridrunner-edge-node-ingest.service /etc/systemd/system/gridrunner-edge-node-ingest.service
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/install -m 0644 */gridrunner/state/gridrunner-plane-tracker.service /etc/systemd/system/gridrunner-plane-tracker.service
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/install -m 0644 */gridrunner/state/gridrunner-plane-tracker.timer /etc/systemd/system/gridrunner-plane-tracker.timer
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/install -m 0644 */gridrunner/state/gridrunner-operator-display.service /etc/systemd/system/gridrunner-operator-display.service
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/systemctl daemon-reload
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/systemctl enable gridrunner-web.service
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/systemctl restart gridrunner-web.service
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/systemctl enable --now gridrunner-events.timer
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/systemctl enable --now gridrunner-edge-node-ingest.service
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/systemctl enable --now gridrunner-plane-tracker.timer
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/systemctl enable gridrunner-operator-display.service
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/systemctl enable --now mosquitto.service
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/systemctl restart gridrunner-events.service
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/nmcli radio wifi on
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/nmcli connection up *
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/nmcli connection down *
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/nmcli connection modify *
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/nmcli connection add *
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/systemctl poweroff
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/systemctl reboot
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/bash */gridrunner/scripts/install-adsb-readsb.sh
$OPERATOR_USER ALL=(root) NOPASSWD: /usr/bin/env GRIDRUNNER_HOME=* GRIDRUNNER_STATE_DIR=* GRIDRUNNER_DISPLAY_VENDOR_DRIVER=* GRIDRUNNER_LCD_SHOW_URL=* /usr/bin/bash */gridrunner/scripts/configure-display.sh *
EOF

chmod 0440 "$SUDOERS_FILE"
visudo -cf "$SUDOERS_FILE"

for group in systemd-journal adm; do
  if getent group "$group" >/dev/null 2>&1; then
    usermod -aG "$group" "$OPERATOR_USER"
  fi
done

echo "GRIDRUNNER sudoers installed for user: $OPERATOR_USER"
echo "Journal access groups updated for user: $OPERATOR_USER"
echo "Log out and back in, or reboot, for new group membership to apply."
